---
include:
  - project: ci-templates-48151/gitlab-ci-templates
    ref: v1.7.2
    file: /lint/commit.yml
  - project: ci-templates-48151/gitlab-ci-templates
    ref: v1.7.2
    file: /lint/markdown.yml
    inputs:
      path: README.md examples/default/README.md
  - project: ci-templates-48151/gitlab-ci-templates
    ref: v1.7.2
    file: /security/gitleaks.yml
  - project: ci-templates-48151/gitlab-ci-templates
    ref: v1.7.2
    file: /validate/tflint.yml
  - project: ci-templates-48151/gitlab-ci-templates
    ref: v1.7.2
    file: /test/renovate.yml
  - project: ci-templates-48151/gitlab-ci-templates
    ref: v1.7.2
    file: /test/trivy.yml
  - project: ci-templates-48151/gitlab-ci-templates
    ref: v1.7.2
    file: /release/semantic.yml
  - template: Jobs/SAST-IaC.latest.gitlab-ci.yml
  - project: ci-templates-48151/gitlab-ci-templates
    ref: v1.7.2
    file: /common/terraform.yml
  - project: ci-templates-48151/gitlab-ci-templates
    ref: v1.7.2
    file: /common/terraform-module.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

stages:
  - lint
  - security
  - test
  - validate
  - release
  - deploy

# lint
commit:
  extends: .lint:commit

markdown:
  extends: .lint:markdown

# security
gitleaks:
  extends: .security:gitleaks

# test
renovate:config-validator:
  extends: .renovate:config-validator

trivy:
  extends: .trivy

# validate
terraform:fmt:
  extends: .terraform:fmt

terraform:validate:
  extends: .terraform:validate

tflint:
  extends: .tflint
  dependencies:
    - terraform:validate

# release
semantic:
  extends: .release:semantic
  artifacts:
    reports:
      dotenv: version.env

# deploy
terraform-module:deploy:
  extends: .terraform-module:deploy
  dependencies:
    - semantic
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      allow_failure: true
